---
title: "Resources"
output: html_document
---

### Links for R and R-Studio

[R](http://www.r-project.org) is a free open-source programming language that can be used for statistical analysis, data-simulation, graphing, and lots of other stuff. Another free program is [R-studio](http://www.rstudio.com), that provides a nice graphic interface for R. Download R first, then download R-studio. Both can run on PCs, Macs or Linux. Students will be learning R in the stats labs using the lab manual []().

### Additional R resources

1. Google is great, Google your problem (literally copy the error you are getting or describe it)
2. [Stackoverflow](https://stackoverflow.com) is great, google will often take you there because someone has already asked your question, and someone else has answered, usually many people have answered your question many ways.
3. I have written a book Mathematics and Programming for Machine Learning with R: From the Ground Up. You can purchase it here [https://www.amazon.com/gp/product/B08JHDCX9Y?pf_rd_r=363HP7AFW10KF1Z3J7YJ&pf_rd_p=6fc81c8c-2a38-41c6-a68a-f78c79e7253f&pd_rd_r=5070c28f-1639-4b78-860d-946327ba8ba6&pd_rd_w=mKq3i&pd_rd_wg=SuQ8M&ref_=pd_gw_unk](https://www.amazon.com/gp/product/B08JHDCX9Y?pf_rd_r=363HP7AFW10KF1Z3J7YJ&pf_rd_p=6fc81c8c-2a38-41c6-a68a-f78c79e7253f&pd_rd_r=5070c28f-1639-4b78-860d-946327ba8ba6&pd_rd_w=mKq3i&pd_rd_wg=SuQ8M&ref_=pd_gw_unk)
4. This is the definitive guide for all things R Markdown (you will find this very useful as you get better at this skill): [https://bookdown.org/yihui/rmarkdown/](https://bookdown.org/yihui/rmarkdown/)

5. You can also look up these links
The easiest GitHub tutorial ever. For those who are not at ease with Git… | by Joos Korstanje | Towards Data Science 
6. Check RStudio forums here: https://support.rstudio.com/hc/en-us
 
### Git Info Links (You have to do a search for these. I couldn't see to past the link in here)

Introduction to Git and GitHub | Coursera 
 

Free Git Tutorial - Intro to Git | Udemy 
 

Git & GitHub - The Complete Git & GitHub Course | Udemy 
 

An Intro to Git and GitHub for Beginners (Tutorial) 
 

Online Courses - Anytime, Anywhere | Udemy 
 

Git: Become an Expert in Git & GitHub in 4 Hours | Udemy 
 

Creating a book manuscript using {bookdown} 
 

Creating websites in R 
 

Hosting an R Markdown Website on Github Pages 
 

Add a new page to R Markdown Website 
 

Tutorial: Intro to Git & GitHub for the R User · bcgov/bcgov-data-science-resources Wiki 
 

How to upload your R code on GitHub: example with an R script on MacOS - Stats and R 
 

Tutorial: Intro to Git & GitHub for the R User · bcgov/bcgov-data-science-resources Wiki 
 

Gerke Lab | Using Netlify CMS with R Markdown, hosted on GitHub Pages 
 

Chapter 7 Introduce yourself to Git | Happy Git and GitHub for the useR 
 

The requested URL returned error: 403 Forbidden · Issue #39 · trilbymedia/grav-plugin-git-sync 

https://www.youtube.com/watch?v=eWxxfttcMts&t=220s

### RMarkdown Links
Rob Hyndman | How Rmarkdown changed my life | RStudio (2020) 
 

(12) How to create a bookdown book in 5 minutes - YouTube 
 

Rmarkdown templates 
 

Gallery 
 

2.1 Example applications | R Markdown: The Definitive Guide 
 

RPubs 
 

Using R Markdown for Class Assignments 
 

2.1 Example applications | R Markdown: The Definitive Guide 
 

Gallery 
 

Using R Markdown for Class Assignments 
 

Gerke Lab | Using Netlify CMS with R Markdown, hosted on GitHub Pages 
 

Merge conflicts: helping data science students merge their advanced skills into existing teams 
 

Using R markdown in R to write Research Papers 
 

